// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Deveel.Link.Models
{

    /// <summary>
    /// Defines values for Currency.
    /// </summary>
    public static class Currency
    {
        public const string NOK = "NOK";
        public const string DKK = "DKK";
        public const string SEK = "SEK";
        public const string EUR = "EUR";
    }
}
