// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Deveel.Link.Models
{

    /// <summary>
    /// Defines values for DataCodingScheme.
    /// </summary>
    public static class DataCodingScheme
    {
        public const string BINARY = "BINARY";
        public const string GSM = "GSM";
        public const string TEXT = "TEXT";
        public const string UC2 = "UC2";
    }
}
