// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Deveel.Link.Models
{

    /// <summary>
    /// Defines values for KeywordType.
    /// </summary>
    public static class KeywordType
    {
        public const string DEFAULT = "DEFAULT";
        public const string EQUALS = "EQUALS";
        public const string FIRSTWORD = "FIRST_WORD";
        public const string STARTSWITH = "STARTS_WITH";
    }
}
