// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Deveel.Link.Models
{

    /// <summary>
    /// Defines values for Priority.
    /// </summary>
    public static class Priority
    {
        public const string HIGH = "HIGH";
        public const string NORMAL = "NORMAL";
        public const string LOW = "LOW";
    }
}
