// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Deveel.Link.Models
{

    /// <summary>
    /// Defines values for RouteType.
    /// </summary>
    public static class RouteType
    {
        public const string KEYWORDROUTE = "KEYWORD_ROUTE";
        public const string SUBNUMBERROUTE = "SUBNUMBER_ROUTE";
    }
}
