// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Deveel.Link.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The result of a SMS Send operation
    /// </summary>
    public partial class SmsSendResult
    {
        /// <summary>
        /// Initializes a new instance of the SmsSendResult class.
        /// </summary>
        public SmsSendResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SmsSendResult class.
        /// </summary>
        /// <param name="messageId">The unique identifier of the message
        /// handled by LINK Mobility</param>
        /// <param name="resultCode">Indicates the code of the </param>
        /// <param name="description">A descriptive message of the
        /// result</param>
        /// <param name="smsCount">The number of SMS messages produced by the
        /// request</param>
        public SmsSendResult(string messageId = default(string), int? resultCode = default(int?), string description = default(string), int? smsCount = default(int?))
        {
            MessageId = messageId;
            ResultCode = resultCode;
            Description = description;
            SmsCount = smsCount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the unique identifier of the message handled by LINK
        /// Mobility
        /// </summary>
        [JsonProperty(PropertyName = "messageId")]
        public string MessageId { get; set; }

        /// <summary>
        /// Gets or sets indicates the code of the
        /// </summary>
        [JsonProperty(PropertyName = "resultCode")]
        public int? ResultCode { get; set; }

        /// <summary>
        /// Gets or sets a descriptive message of the result
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets the number of SMS messages produced by the request
        /// </summary>
        [JsonProperty(PropertyName = "smsCount")]
        public int? SmsCount { get; set; }

    }
}
