// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Deveel.Link.Models
{

    /// <summary>
    /// Defines values for TypeOfNumber.
    /// </summary>
    public static class TypeOfNumber
    {
        public const string ALPHANUMERIC = "ALPHANUMERIC";
        public const string SHORTCODE = "SHORTCODE";
        public const string MSISDN = "MSISDN";
    }
}
